service: slack-pdf-upload
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GOOGLE_DRIVE_FOLDER_ID: ${env:GOOGLE_DRIVE_FOLDER_ID}
functions:
  upload:
    handler: dist/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
